[build]
  base = "client"
  publish = "dist"
  command = "yarn build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express", "cors", "dotenv", "body-parser", "serverless-http", "firebase"]
