export enum Routes {
  CAREER = "/career",
  CONFS = "/confs",
  CONTACT = "/contact",
  COFFEE = "https://www.buymeacoffee.com/helvira",
  GITHUB = "https://github.com/HelviraG",
  HOME = "/",
  LINKEDIN = "https://www.linkedin.com/in/helvira-dev",
  LIVE = "/lives",
  PASSION = "/explore/passion",
  NOT_FOUND_PASSION = "/explore/passion/*",
  PRESS = "/press",
  QUIZ = "/explore/passion/whoami",
  QUIZ_INIT = "/explore/passion/whoami/init",
  QUIZ_STEP = "/explore/passion/whoami/:cat/:id",
  TWITTER = "https://twitter.com/helvira_g",
  EXPLORE = "/explore",
  QUIZ_RESULT = "/whoarewe",
}
