// eslint-disable-next-line no-unused-vars
export enum Tags {
  ALL = "all",
  BEGINNER = "beginner",
  BLOG = "blog",
  CHALLENGES = "challenges",
  DEVFEST = "devfest",
  DISCOVERY = "discovery",
  ENGINEERING = "engineering",
  ENGLISH = "EN",
  FRENCH = "FR",
  HUMAN_TECH = "human & tech",
  INTERVIEW = "interview",
  LIVE = "live",
  MOTIVATION_CALL = "motivationcall",
  PASSION = "passion",
  PRESS = "press",
  PUB = "pub",
  QUICKY = "quicky",
  QUIZ = "quiz",
  REPLAY = "replay",
  TALK = "talk",
  TECH = "tech",
  TECH_NOCODE = "tech & nocode",
  TESTIMONY = "testimony",
  VIDEO = "video",
  WOMEN = "femmes",
  WOMEN_IN_TECH = "womenintech",
  YEAR = "year",
  INSPIRATION = "inspiration",
}